CREATE TABLE USER_FM (
    ID NUMBER,
    CONSTRAINT USER_FM_PK PRIMARY KEY(ID),
    FIRST_NAME NVARCHAR2(50),
    LAST_NAME NVARCHAR2(50),
    PHONE NVARCHAR2(50),
    COUNTRY NVARCHAR2(20),
    CITY NVARCHAR2(20),
    AGE NUMBER,
    DATE_REGISTERED TIMESTAMP,
    DATE_LAST_ACTIVE TIMESTAMP,
    RELATIONSHIP_STATUS NVARCHAR2(10),
    RELIGION NVARCHAR2(20),
    SCHOOL NVARCHAR2(50),
    UNIVERSITY NVARCHAR2(50)
);

CREATE SEQUENCE USER_FM_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;