CREATE TABLE MESSAGE (
    ID NUMBER,
    CONSTRAINT MESSAGE_PK PRIMARY KEY(ID),
    TEXT NVARCHAR2(200),
    DATE_SENT TIMESTAMP,
    DATE_READ TIMESTAMP,
    USER_FROM_ID NUMBER NOT NULL,
    CONSTRAINT USER_FROM_FK FOREIGN KEY(USER_FROM_ID) REFERENCES USER_FM(ID),
    USER_TO_ID NUMBER NOT NULL,
    CONSTRAINT USER_TO_FK FOREIGN KEY(USER_TO_ID) REFERENCES USER_FM(ID)
);

CREATE SEQUENCE MESSAGE_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;