CREATE TABLE POST (
    ID NUMBER,
    MESSAGE NVARCHAR2(200),
    DATE_POSTED TIMESTAMP,
    USER_POSTED_ID NUMBER NOT NULL,
    CONSTRAINT USER_POSTED_FK FOREIGN KEY(USER_POSTED_ID) REFERENCES USER_FM(ID)
);

CREATE SEQUENCE POST_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;
