CREATE TABLE POST_USER_TAG(
    POST_ID NUMBER,
    CONSTRAINT POST_USER_POST_FK FOREIGN KEY(POST_ID) REFERENCES POST(ID),
    USER_ID NUMBER,
    CONSTRAINT POST_USER_USER_FK FOREIGN KEY(USER_ID) REFERENCES USER_FM(ID)
);